### ISSUE TITLE
[Question] "child most" atom with getter/setter not updating to new values.

### ISSUE THREAD

**Issue by Noitidart** [pmndrs/jotai#277]
I was trying to make the child most atom read from a cache. My full code is below and playground too.

The code of interest is:

```
let cachedValue = "init";
const enabledAtom = atom(
  (get) => cachedValue,
  (get, set, nextValue) => {
    cachedValue = nextValue;
    return cachedValue;
  }
);
```

However using the `useAtom(enabledAtom)` and then doing `setEnabled(true)` is not changing the value ever. May you please help me understand why?

https://codesandbox.io/s/jotai-privative-geter-seter-playground-pitux?file=/src/App.js

```
let cachedValue = "init";
const enabledAtom = atom(
  (get) => cachedValue,
  (get, set, nextValue) => {
    cachedValue = nextValue;
    return cachedValue;
  }
);

function Atomed() {
  useAtom(enabledAtom);
  const [enabled, setEnabled] = useAtom(enabledAtom);
  return (
    <>
      <div>{String(enabled)}</div>
      <div>
        <button
          type="button"
          onClick={() => {
            setEnabled(!enabled);
          }}
        >
          {enabled ? "Disable" : "Enable"}
        </button>
      </div>
    </>
  );
}
export default function App() {
  return (
    <Provider>
      <div className="App">
        <Suspense fallback="Loading...">
          <Atomed />
        </Suspense>
      </div>
    </Provider>
  );
}
```

**Comment by dai-shi** [comment]
> The code of interest is:

Just looking at this, you assumption is probably not correct.
The `catchedValue` is a module variable and not reactive.
Unless intentional, it's not a recommended pattern because it's shared by multiple providers.

The `atom` function creates what I call "atom config", and it doesn't hold any values. It's a provider that holds all values.

Your atom `read` function is this.
```js
  (get) => cachedValue,
```
Provider will run this at the first time of the use, just once. It will never re-evaluate the `read` function.

**Comment by Noitidart** [comment]
Oh real intersting, I fixed it by doing `set` on the atom itself, instead of returning it.

So the return from setters is insignficant I think?

Thanks for your speedy response!

```
const enabledAtom = atom(
  async (get) => cachedValue,
  async (get, set, nextValue) => {
    cachedValue = nextValue;
    set(enabledAtom, cachedValue); ////// this fixed it - used to return it before
  }
);
```

**Comment by dai-shi** [comment]
Ah, I missed that part. Yeah, you need to `set` it. You can only return a promise or void.
But, your code is still not a suggested pattern. It's a derived atom without dependency. You shouldn't set a derived atom by itself. It happens to work because it has no dependency (= `get` is not used in `read`.)

```js
const enabledAtom = atom(
  "init",
  async (get, set, nextValue) => {
    cachedValue = nextValue;
    set(enabledAtom, cachedValue);
  }
);
```

This is better, but we don't document this usage because TypeScript complains by its design.

We have a util for this pattern instead.

```js
const enabledAtom = atomWithReducer(
  "init",
  (nextValue) => {
    cachedValue = nextValue;
    return nextValuue;
  }
);
```

**Comment by Noitidart** [comment]
Oh thank you. I think I recall that from the persist docs.

The reason why I needed a getter for the first argument to atom, is because on first read I want to asynhronously read from disk. (reworking that persist atom thing).


```
const enabledAtom = atom(
  async () => cached ? cachedValue : readFromDisk(), /////// here is where i do async
  async (get, set, nextValue) => {
    cachedValue = nextValue;
    set(enabledAtom, cachedValue);
  }
);
```

**Comment by dai-shi** [comment]
Here's a quick one:
```js
const cacheAtom = atom(null)
const enabledAtom = atom(
  (get) => get(cacheAtom) || readFromDisk(), // readFromDisk returns a promise
  (get, set, nextValue) => {
    set(cacheAtom, nextValue)
    // you can saveToDisk(nextValue)
  }
)
```

**Comment by Noitidart** [comment]
Oh gosh yes this is straight from docs I should just follow that haha.
Thank you Ill update it to this!
